package com.alperenbabagil.cleanappbase.detail.presentation

import com.alperenbabagil.cleanappbase.detail.presentation.changepp.changePPPresentationModule
import com.alperenbabagil.cleanappbase.detail.presentation.profiledetail.profileDetailPresentationModule

val detailPresentationModule = profileDetailPresentationModule + changePPPresentationModule